batch_size: 12
data_specs:
  channels: 4
  data_workers: null
  dtype: null
  height: 256
  image_type: zscore
  is_categorical: false
  label_type: mask
  mask_channels: 1
  rescale: false
  rescale_maxima: auto
  rescale_minima: auto
  val_holdout_frac: 0.2
  width: 256
infer: true
inference:
  output_dir: C:\Users\Brian\Documents\GitHub\DSC672\temp_data\inference_out\
  window_step_size_x: null
  window_step_size_y: null
inference_augmentation:
  augmentations:
    DropChannel:
      axis: 2
      idx: 3
    Normalize:
      max_pixel_value: 255.0
      mean:
      - 0.4694540883980545
      - 0.39878097047992783
      - 0.37210627163157745
      p: 1.0
      std:
      - 0.5592284947687913
      - 0.46570573093063344
      - 0.4358853575316516
  p: 1.0
inference_data_csv: C:\Users\Brian\Documents\GitHub\DSC672\temp_data\solaris_inference_file.csv
model_name: xdxd_spacenet4
model_path: null
nn_framework: torch
pretrained: true
train: true
training:
  callbacks:
    model_checkpoint:
      filepath: C:\Users\Brian\Documents\GitHub\DSC672\temp_data\xdxd_best.pth
      monitor: val_loss
  checkpoint_frequency: 10
  epochs: 60
  loss:
    bcewithlogits: null
    jaccard: null
  loss_weights:
    bcewithlogits: 10
    jaccard: 2.5
  lr: 1e-4
  metrics:
    training: null
    validation: null
  model_dest_path: C:\Users\Brian\Documents\GitHub\DSC672\temp_data\xdxd.pth
  opt_args: null
  optimizer: Adam
  steps_per_epoch: null
  verbose: true
training_augmentation:
  augmentations:
    DropChannel:
      axis: 2
      idx: 3
    HorizontalFlip:
      p: 0.5
    Normalize:
      max_pixel_value: 255.0
      mean:
      - 0.4694540883980545
      - 0.39878097047992783
      - 0.37210627163157745
      p: 1.0
      std:
      - 0.5592284947687913
      - 0.46570573093063344
      - 0.4358853575316516
    RandomCrop:
      height: 256
      p: 1.0
      width: 256
    RandomRotate90:
      p: 0.5
  p: 1.0
  shuffle: true
training_data_csv: C:\Users\Brian\Documents\GitHub\DSC672\temp_data\solaris_training_file.csv
validation_augmentation:
  augmentations:
    CenterCrop:
      height: 256
      p: 1.0
      width: 256
    DropChannel:
      axis: 2
      idx: 3
    Normalize:
      max_pixel_value: 255.0
      mean:
      - 0.4694540883980545
      - 0.39878097047992783
      - 0.37210627163157745
      p: 1.0
      std:
      - 0.5592284947687913
      - 0.46570573093063344
      - 0.4358853575316516
  p: 1.0
validation_data_csv: null
