batch_size: 8
data_specs:
  channels: 4
  data_workers: null
  dtype: null
  height: 256
  image_type: zscore
  is_categorical: false
  label_type: mask
  mask_channels: 1
  rescale: false
  rescale_maxima: auto
  rescale_minima: auto
  val_holdout_frac: 0.2
  width: 256
infer: true
inference:
  output_dir: temp_data/inference_out/
  window_step_size_x: null
  window_step_size_y: null
inference_augmentation:
  augmentations:
    DropChannel:
      axis: 2
      idx: 3
    Normalize:
      max_pixel_value: 255.0
      mean:
      - 0.4849550349291633
      - 0.485635239909677
      - 0.4044555221912907
      p: 1.0
      std:
      - 0.19496345243155164
      - 0.18244518105697646
      - 0.1934076933773876
  p: 1.0
inference_data_csv: temp_data/run1_solaris_inference_file.csv
model_name: xdxd_spacenet4
model_path: null
nn_framework: torch
pretrained: true
train: true
training:
  callbacks:
    model_checkpoint:
      filepath: temp_data/xdxd_fix_best.pth
      monitor: val_loss
  checkpoint_frequency: 10
  epochs: 40
  loss:
    bcewithlogits: null
    jaccard: null
  loss_weights:
    bcewithlogits: 10
    jaccard: 2.5
  lr: 1e-4
  metrics:
    training: null
    validation: null
  model_dest_path: temp_data/xdxd_fix_best_epoch32_2.4549999237060547.pth
  opt_args: null
  optimizer: Adam
  steps_per_epoch: null
  verbose: true
training_augmentation:
  augmentations:
    DropChannel:
      axis: 2
      idx: 3
    HorizontalFlip:
      p: 0.5
    Normalize:
      max_pixel_value: 255.0
      mean:
      - 0.4849550349291633
      - 0.485635239909677
      - 0.4044555221912907
      p: 1.0
      std:
      - 0.19496345243155164
      - 0.18244518105697646
      - 0.1934076933773876
    RandomCrop:
      height: 256
      p: 1.0
      width: 256
    RandomRotate90:
      p: 0.5
  p: 1.0
  shuffle: true
training_data_csv: temp_data/run1_solaris_training_file.csv
validation_augmentation:
  augmentations:
    CenterCrop:
      height: 256
      p: 1.0
      width: 256
    DropChannel:
      axis: 2
      idx: 3
    Normalize:
      max_pixel_value: 255.0
      mean:
      - 0.4849550349291633
      - 0.485635239909677
      - 0.4044555221912907
      p: 1.0
      std:
      - 0.19496345243155164
      - 0.18244518105697646
      - 0.1934076933773876
  p: 1.0
validation_data_csv: null
