batch_size: 10
data_specs:
  channels: 4
  data_workers: null
  dtype: null
  height: 256
  image_type: zscore
  is_categorical: false
  label_type: mask
  mask_channels: 1
  rescale: false
  rescale_maxima: auto
  rescale_minima: auto
  val_holdout_frac: 0.3
  width: 256
infer: true
inference:
  output_dir: temp_data/temp_test/inference_out/
  window_step_size_x: null
  window_step_size_y: null
inference_augmentation:
  augmentations:
    DropChannel:
      axis: 2
      idx: 3
    Normalize:
      max_pixel_value: 255.0
      mean:
      - 0.4752724392821736
      - 0.47921707418377035
      - 0.4066859953361776
      p: 1.0
      std:
      - 0.20380653575313712
      - 0.19179939205042276
      - 0.20130653782646712
  p: 1.0
inference_data_csv: temp_data/solaris_inference_file.csv
model_name: xdxd_spacenet4
model_path: null
nn_framework: torch
pretrained: true
train: true
training:
  callbacks:
    model_checkpoint:
      filepath: temp_data/xdxd_samp_best.pth
      monitor: val_loss
  checkpoint_frequency: 10
  epochs: 60
  loss:
    bcewithlogits: null
    jaccard: null
  loss_weights:
    bcewithlogits: 10
    jaccard: 2.5
  lr: 1e-4
  metrics:
    training: null
    validation: null
  model_dest_path: temp_data/sampling.pth
  opt_args: null
  optimizer: Adam
  steps_per_epoch: null
  verbose: true
training_augmentation:
  augmentations:
    DropChannel:
      axis: 2
      idx: 3
    Normalize:
      max_pixel_value: 255.0
      mean:
      - 0.4752724392821736
      - 0.47921707418377035
      - 0.4066859953361776
      p: 1.0
      std:
      - 0.20380653575313712
      - 0.19179939205042276
      - 0.20130653782646712
  p: 1.0
  shuffle: true
training_data_csv: temp_data/solaris_training_file.csv
validation_augmentation:
  augmentations:
    DropChannel:
      axis: 2
      idx: 3
    Normalize:
      max_pixel_value: 255.0
      mean:
      - 0.4752724392821736
      - 0.47921707418377035
      - 0.4066859953361776
      p: 1.0
      std:
      - 0.20380653575313712
      - 0.19179939205042276
      - 0.20130653782646712
  p: 1.0
validation_data_csv: null
