model_name: xdxd_spacenet4

model_path:
train: true
infer: true

pretrained: true
nn_framework:  torch
batch_size: 1

data_specs:
  width: 256
  height:  256
  dtype:
  image_type: zscore
  rescale: false
  rescale_minima: auto
  rescale_maxima: auto
  channels: 4
  label_type: mask
  is_categorical: false
  mask_channels: 1
  val_holdout_frac: 0.2
  data_workers:

training_data_csv: 'temp_data/solaris_training_file.csv'
validation_data_csv:
inference_data_csv: 'temp_data/solaris_inference_file.csv'

training_augmentation:
  augmentations:
    DropChannel:
      idx: 3
      axis: 2
    HorizontalFlip:
      p: 0.5
    RandomRotate90:
      p: 0.5
    RandomCrop:
      height: 256
      width: 256
      p: 1.0
    Normalize:
      mean:
        - 0.465824
        - 0.395090
        - 0.368441
      std:
        - 0.303092
        - 0.239203
        - 0.224330
      max_pixel_value: 255.0
      p: 1.0
  p: 1.0
  shuffle: true
validation_augmentation:
  augmentations:
    DropChannel:
      idx: 3
      axis: 2
    CenterCrop:
      height: 256
      width: 256
      p: 1.0
    Normalize:
      mean:
        - 0.465824
        - 0.395090
        - 0.368441
      std:
        - 0.303092
        - 0.239203
        - 0.224330
      max_pixel_value: 255.0
      p: 1.0
  p: 1.0
inference_augmentation:
  augmentations:
    DropChannel:
      idx: 3
      axis: 2
    Normalize:
      mean:
        - 0.465824
        - 0.395090
        - 0.368441
      std:
        - 0.303092
        - 0.239203
        - 0.224330
      max_pixel_value: 255.0
      p: 1.0
  p: 1.0
training:
  epochs:  1
  steps_per_epoch:
  optimizer: Adam
  lr: 1e-4
  opt_args:
  loss:
    bcewithlogits:
    jaccard:
  loss_weights:
    bcewithlogits: 10
    jaccard: 2.5
  metrics:
    training:
    validation:
  checkpoint_frequency: 10
  callbacks:
    model_checkpoint:
      filepath: 'temp_data/xdxd_best.pth'
      monitor: val_loss
  model_dest_path: 'temp_data/xdxd_long60.pth'
  verbose: true

inference:
  window_step_size_x:
  window_step_size_y:
  output_dir: 'temp_data/inverence_out/inference_out/'